language: android
jdk: oraclejdk8
sudo: false

branches:
  only:
  - master
  - develop

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-24.0.1
#    - android-22
    - android-24
#    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug
#  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#  - emulator -avd test -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
#  - ./gradlew connectedDevelopDebugAndroidTest
